### ISSUE TITLE
Potential dataloader bug

### ISSUE THREAD

**Issue by nicolemcnally** [TooTouch/REVECA#1]
In line 233 ---> https://github.com/TooTouch/REVECA/blob/603bca9e853bc2bb8726ffb7bf7f8fca321941f1/REVECA/build_dataset.py#L233
it seems this should be label_ids, not input_ids.

**Comment by TooTouch** [comment]
@nicolemcnally 

Thank you for pointing the wrong case.
I really appreciate your comment.

I corrected it after checking the wrong part, so please refer to https://github.com/TooTouch/REVECA/commit/970bc48a191cd499251adec376f0c7d3eb9d7a6e#.

**Comment by tootouch** [comment]
@nicolemcnally 

Thank you for pointing the wrong case.
I really appreciate your comment.

I corrected it after checking the wrong part, so please refer to https://github.com/TooTouch/REVECA/commit/970bc48a191cd499251adec376f0c7d3eb9d7a6e#.
